# Generated by Django 4.2.10 on 2025-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('codigo_equipamento', models.CharField(max_length=50)),
                ('codigo_servico', models.CharField(max_length=50)),
                ('data_abertura', models.DateTimeField()),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.DurationField()),
                ('descricao', models.TextField()),
                ('incidente', models.CharField(max_length=50)),
                ('origem', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('subcategoria', models.CharField(max_length=100)),
                ('subcategoria_detalhe', models.CharField(max_length=200)),
                ('tipo_contato', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'f_incidente',
            },
        ),
    ]
