# Generated by Django 4.2.10 on 2025-01-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='aberto_por',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidente',
            name='fila',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
