from .cliente_serializer import ClienteSerializer
from .contrato_serializer import ContratoSerializer
from .equipamento_serializer import EquipamentoSerializer
from .grupo_economico import GrupoEconomicoSerializer
from .licenca_serializer import LicencaSerializer
from .link_serializer import LinkSerializer
from .servico_serializer import ServicoSerializer
from .site_serializer import SiteSerializer
