# Generated by Django 4.2.10 on 2025-01-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vantive_id', models.CharField(max_length=50)),
                ('razao_social', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'db_table': 'd_grupo_economico',
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vantive_id',
            field=models.CharField(max_length=50),
        ),
    ]
