# Generated by Django 4.2.10 on 2025-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_contrato_rename_tipo_servico_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenca',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
