# Generated by Django 4.2.10 on 2025-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_licenca_status_link_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='tipo_negocio',
        ),
        migrations.AddField(
            model_name='site',
            name='cnpj',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='razao_social',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
